### ISSUE TITLE
improvement: take off the "prints"

### ISSUE THREAD

**Issue by felpsio** [giandifra/clustering_google_maps#13]
Hi,

Thanks for the package :D.

I noticed that the package has lots of prints show list length, aggregation length etc. Probably to help debug, but it can decrease the performance while in production. Would be nice to take off these print or make it be executed only while in debugMode.

Usually  I use this function to check if is DebugMode:
```
bool get isInDebugMode {
  bool inDebugMode = false;
  assert(inDebugMode = true);
  return inDebugMode;
}
```

**Comment by giandifra** [comment]
I remove print in release mode!

Thanks!
