### ISSUE TITLE
NoSuchMethodError: The method 'getVisibleRegion' was called on null.

### ISSUE THREAD

**Issue by maxouille** [giandifra/clustering_google_maps#17]
Hi, 

I added the `aggregationSetup: AggregationSetup()` argument to make the new release work. However, aggretation is not working anymore. I got this log which seems to cause the problem : 

`NoSuchMethodError: The method 'getVisibleRegion' was called on null.`

It looks like the `mapController` is null. In the file clustering_helper.dart, `mapController` is not initialized anywhere. Is this normal ? 

Could you please help me to solve this ?

Thx

EDIT : it appears that "mapController" is not defined in `clustering_helper.dart`. It is declared but never assigner. I think it should be passed as an argument when instantiating the ClusteringHelper class. If i'm right, lib must be updated

**Comment by xni06** [comment]
I have the same issue

**Comment by maxouille** [comment]
Forgot to add  `clusteringHelper.mapController = mapController;` in onMapCreated !
