### ISSUE TITLE
Markers aggregation radius

### ISSUE THREAD

**Issue by Andreigr0** [giandifra/clustering_google_maps#20]
![SVID_20191029_121952_1](https://user-images.githubusercontent.com/44437712/67754136-f5ccb880-fa46-11e9-9ad7-c81e286a3af8.gif)
I'm trying to setup aggregation max zoom limits for clustering. But when zoom level is above 13.5 it stops clustering. When I set another values (for example [5.0, 7.5, 10.5, 13.0, 13.5, 14.5, 15.5] instead of standard [ 3.0, 5.0, 7.5, 10.5, 13.0, 13.5, 14.5]) nothing changes.
Because of that app starts lagging.
How to clustering at zoom level above, for example, 15.0?

**Comment by r4ptus** [comment]
when u init ur ClusterHelper there is a variable called maxZoomForAggregatePoints try setting this up
