### ISSUE TITLE
Update Google Maps Package Dependency Version

### ISSUE THREAD

**Issue by JayPerfetto** [giandifra/clustering_google_maps#24]
Please update the Google Maps dependency version to   google_maps_flutter: ^0.5.28+1
so that this may be used with other google maps packages that depend on a higher version of google maps than this one does.

**Comment by petekblaz** [comment]
+1

**Comment by Mellowz** [comment]
+1 pls update

**Comment by behrad84** [comment]
I'm facing the same issue on latest   google_maps_flutter: ^1.0.3 , could it to be updated ASAP ?

**Comment by behrad84** [comment]
I just opened new PR #25 which should address this issue. @giandifra please review this.
