### ISSUE TITLE
Need to custom Markers or at least i can execute onTap inside Marker()

### ISSUE THREAD

**Issue by agil3st** [giandifra/clustering_google_maps#26]
i need to override onTap in this Marker()

`
Future<void> updateAggregatedPoints({double zoom = 0.0}) async {
  ....
  for (var i = 0; i < aggregation.length; i++) {
     ...
     final marker = Marker(
        markerId: markerId,
        position: a.location,
        infoWindow: InfoWindow(title: a.count.toString()),
        icon: bitmapDescriptor,
        onTap: , // need this
      );
  }
}
`

**Comment by jeromeDms** [comment]
Here is how I achieved this so I can display a custom info window using  custom_info_window package :


```
_updateMarkers(Set<Marker> markers) {
    setState(() {
      this.markers = markers
          .map((clusterMarker) => () {
            if(clusterMarker.markerId.value.endsWith("_1")) {
              int nbMarkers = allAntennasItems.length;
              for (var i = 0; i < nbMarkers; i++) {
                var marker = allAntennasItems[i];
                if (marker.latLng == clusterMarker.position) {
                  return clusterMarker.copyWith(
                    onTapParam:(){ _customInfoWindowController.addInfoWindow!(getInfoWindow(marker), marker.latLng); },
                   );
                }
              }
           }
            return clusterMarker;
          }())
          .toSet();
    });
  }
```

![untitled](https://user-images.githubusercontent.com/19860492/157226583-db150581-b1aa-4826-bd93-418ab4028714.gif)
