### ISSUE TITLE
Dependency error with google_maps_flutter: ^0.5.7

### ISSUE THREAD

**Issue by DemianSteelstone** [giandifra/clustering_google_maps#6]
Hi!
I have some problems with your plugin.
I need to use google_maps_flutter: ^0.5.7 and it's not working.

From console:

Because clustering_google_maps 0.0.4+2 depends on google_maps_flutter 0.4.0 and no versions of clustering_google_maps match >0.0.4+2 <0.1.0, clustering_google_maps ^0.0.4+2 requires google_maps_flutter 0.4.0.
So, because manager_mobile_client depends on both google_maps_flutter ^0.5.7 and clustering_google_maps ^0.0.4+2, version solving failed.

**Comment by giandifra** [comment]
I will update soon (in this weekend), sorry for delay.

You can override the dependencies: [see this comment](https://github.com/johnpryan/flutter_map/issues/31#issuecomment-385496322)

**Comment by DemianSteelstone** [comment]
Ok, thanks
