### ISSUE TITLE
Error: aggregation length 1 although it should be more

### ISSUE THREAD

**Issue by maxouille** [giandifra/clustering_google_maps#8]
Hi, 

I'm using this plugin on my flutter app and it's great. However, I think there is a problem with the initial zoom. Indeed, when I set a zoom at 12 like below, there is only one big marker. And I need to move the map with my finger of zoom in/out to make the different cluster appears. 

```
static final CameraPosition _kInitialPosition = const CameraPosition(
    // Paris position by default
    target: LatLng(48.8534, 2.3488),
    zoom: 12.0,
  );
```

I did exactly like the example so I don't know if this happens to you as well.

Best

**Comment by giandifra** [comment]
i try you code, with my example i not see the problem...

**Comment by maxouille** [comment]
I'll go back to my code later and see if something differs from your example. 

Thanks
